coverage:
  ignore:
    - "**/generated/**/*"
    - "**/examples/**/*"
    - "**/test/**/*"
  status:
    patch: false
    project:
      default:
        target: auto
        threshold: 0.05%
        base: auto
        paths:
          - "src"
        if_ci_failed: error
        informational: false
        only_pulls: true

comment:
  layout: "header, diff, changes, uncovered"

